### ISSUE TITLE
Github Action does not stop, when the `duration` is more than 46 seconds

### ISSUE THREAD

**Issue by volchkovk** [grafana/setup-k6-action#15]
Dear Support, 

It seems, I found an issue. Could you please take a look?

When I execute the script with `duration: '47s'`, then the job in Guthub Action does not stop. But when I change the `duration: '46s'`, then the job finishes its work. 

The `k6/browser-test.js` file:

```
import { browser } from "k6/browser"
import { check } from "k6"
import http from "k6/http"

export const options = {
  scenarios: {
    ui: {
      exec: 'openFrontend',
      executor: 'constant-vus',
      vus: 1,
      duration: '47s',
      options: {
        browser: {
          type: 'chromium',
        }
      }
    },
    load: {
      exec: 'load',
      executor: 'ramping-arrival-rate',
      startRate: 1,
      timeUnit: '1s',
      preAllocatedVUs: 10,
      stages: [
        { target: 5, duration: '10s' },
        { target: 10, duration: '30s' },
        { target: 10, duration: '30s' },
        { target: 3, duration: '10s' },
      ]
    }
  },
  summaryTrendStats: ["avg", "min", "med", "max", "p(90)", "p(95)", "p(99)", "count"],
  thresholds: {
    http_req_failed: ["rate<0.01"], // http errors should be less than 1%
  },
}

export async function openFrontend() {
  const context = await browser.newContext()
  const page = await context.newPage()

  try {
    await page.goto("put-your-URL-here")
    await page.locator("put-your-locator-here").click()

  } finally {
    await page.close()
  }
}

export function load() {
  const res = http.get('put-your-URL-here')

  check(res, {
    "status was 200": (r) => r.status === 200,
  })
}
```

And the `load_test_browser.yaml`:

```
name: Browser Load Test

on:
  push:
    branches:
      - "**"

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
        with:
          browser: true
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: k6/browser-test.js

```
